from .utils import valid_denominator_sets, is_valid_denominator_set
from itertools import permutations
from .fraction_vector import FractionVector, ModFractionVector
from .fraction import Fraction
from .cyclic_group import CyclicGroup

from typing import Iterable


class KVecGeneratingSet():
    """Implements a method for identifying the unique k-vectors that
    generate unique sublattices. This essentially follows the process
    outlined on the top of page 34 of David's thesis. The summary paragraph
    is reproduced here:

    >    Summarizing these findings, k can only be generated by k = ki ∈< k > + z ∈ Z3.
    >    Thus,  to enumerate all  k sub-lattices of index N it is sufficient to
    >    construct all possible ⃗k vectors with coordinates ci = mi/ni ∈ [0, 1)
    >    satisfying lcm({ni}) = N . From this set of ⃗k, we ca  successively filte
    >    out all other ki ∈< k > so that only one representative from each
    >    cyclic  group remains. This final set of k represents all distinct
    >    k sublattices of index N.

    The key steps are:
    1. Identify sets of three denominators such that lcm({denoms}) = N
    2. For each set of three denominators, get all of its permutations
    3. For every denominator permutation, enumerate vectors whose elements are
       less than one (i.e. c_i = m_i / n_i in [0, 1))
    4. A "cyclic group" is what you get by repeatedly adding one of these vectors to
       itself and mod 1'ing the result (to bring the coordinates back into [0, 1) )
       (only storing the vecs that adhere to the lcm rule above)
    5. For each vector from step 3, compute it's cyclic group
    6. Keep track of the unique cyclic groups
    7. Choose one representative from each of these CyclicGroups.
    """

    @classmethod
    def from_sublattice_index(cls, N: int):
        denominator_sets = valid_denominator_sets(N)
        cyclic_groups: set[CyclicGroup] = set()
        for denominator_set in denominator_sets:
            denom_orderings = permutations(denominator_set)
            for denoms in denom_orderings:
                for m_1 in range(0, denoms[0]):
                    for m_2 in range(0, denoms[1]):
                        for m_3 in range(0, denoms[2]):
                            vec = ModFractionVector([
                                Fraction(m_1, denoms[0]),
                                Fraction(m_2, denoms[1]),
                                Fraction(m_3, denoms[2])
                            ])
                            reduced_denoms = [f.denom for f in vec.coords]
                            if is_valid_denominator_set(reduced_denoms, N):
                                cyclic_groups.add(CyclicGroup.from_generator(vec, N))

        return cls(cyclic_groups)

    def __init__(self, cgs: Iterable[CyclicGroup]):
        Ns = set([cg.N for cg in cgs])
        if not len(Ns) == 1:
            raise ValueError("SublatticeGeneratingSet instantiated with cyclic groups of varying index!")
        
        self._cyclic_groups = frozenset(cgs)
    
    @property
    def representatives(self) -> list[FractionVector]:
        reps = [cg.representative for cg in self._cyclic_groups]
        return sorted(reps, key=lambda r: r.sortable_string())
    
    def __eq__(self, other: 'KVecGeneratingSet'):
        return self._cyclic_groups == other._cyclic_groups